// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyXDgLgh2m3JbqYA7svj5qorqURUeGHX0',
    appId: '1:1084932223956:web:8f470c266e3a4aff615c41',
    messagingSenderId: '1084932223956',
    projectId: 'flutter-notes-app-6ef40',
    authDomain: 'flutter-notes-app-6ef40.firebaseapp.com',
    storageBucket: 'flutter-notes-app-6ef40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPh_hz_EYp9rD8FLwW-baiVar3qNVAKYo',
    appId: '1:1084932223956:android:afa10b74d64a13cb615c41',
    messagingSenderId: '1084932223956',
    projectId: 'flutter-notes-app-6ef40',
    storageBucket: 'flutter-notes-app-6ef40.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyXDgLgh2m3JbqYA7svj5qorqURUeGHX0',
    appId: '1:1084932223956:web:c04b96838d352207615c41',
    messagingSenderId: '1084932223956',
    projectId: 'flutter-notes-app-6ef40',
    authDomain: 'flutter-notes-app-6ef40.firebaseapp.com',
    storageBucket: 'flutter-notes-app-6ef40.firebasestorage.app',
  );

}